### PR TITLE
Challenge One Complete

### PR DESCRIPTION
**Pull request by AlexKing11**
Please add my hard work into the master branch so we can all use the code for driving our robot :D

A program consisting of a gamepad interfacing with a motor, as well as button functionality to disable the motor.

And Lily is awesome

### CODE REVIEW

**Comment by Kermes05** [comment]
THIS IS BAD, WE NEED TO OPERATE MORE THAN 1 MOTOR AT A TIME, BE FAST. Also, Lily is SUPER not awesome at hamis.
Spider legs are awesome
Spider legs are however not very useful

**Comment by BumbleWyrm** [comment]
Too long, badly written, inefficient. Bad job, Dillon

**Comment by Kermes05** [comment]
We also DO NOT NEED to be able to stop the motor for specifically 2 seconds at a time, we are very unhappy and will very much be giving you a pay cut.

**Comment by AlexKing11** [comment]
I want to see you do better than BumbleWyrm!!!

**Comment by AlexKing11** [comment]
Take up that issue with Colly, he specifically requested the two second cut out window.

**Comment by AlexKing11** [comment]
Guys this is cyberbullying :(
pls stop :(
also stop editing and deleting comments

**Comment by Kermes05** [comment]
We are very sorry and will no longer be editing or deleting comments unless the comment contains very upsetting material inside. Please remember that the person behind the computer is a real person. The only people allowed to be Major bullied is people that have the name "Dillon"

**Comment by AlexKing11** [comment]
D:

**Pull request closed without merging**
